/**
 * Rotulos e classificacao das ações de auditoria.
 *
 * Vive separado de `audit.ts` porque este modulo e consumido também por
 * client components, e `audit.ts` importa `next/headers`, que so roda no
 * servidor.
 */

export const AUDIT_LABELS: Record<string, string> = {
  'login.success': 'Login realizado',
  'login.failure': 'Tentativa de login falhou',
  'logout': 'Logout',
  'account.connected': 'Conta conectada',
  'account.deleted': 'Conta removida',
  'account.synced': 'Conta ressincronizada',
  'project.created': 'Projeto conectado',
  'project.provisioned': 'Projeto criado na Supabase',
  'project.updated': 'Projeto atualizado',
  'project.paused': 'Projeto pausado',
  'project.restored': 'Projeto restaurado',
  'project.archived': 'Projeto arquivado',
  'project.keys_revealed': 'Chaves reveladas',
  'client.created': 'Cliente criado',
  'client.updated': 'Cliente atualizado',
  'client.deleted': 'Cliente removido',
  'data.row_inserted': 'Linha inserida',
  'data.row_updated': 'Linha editada',
  'data.row_deleted': 'Linha excluída',
  'sql.executed': 'SQL executado',
  'sql.migration_applied': 'Migração aplicada',
  'auth.user_created': 'Usuário criado (Auth)',
  'auth.user_updated': 'Usuário alterado (Auth)',
  'auth.user_deleted': 'Usuário excluído (Auth)',
  'storage.file_deleted': 'Arquivo excluído',
  'storage.file_uploaded': 'Arquivo enviado',
  'storage.bucket_created': 'Bucket criado',
  'function.deployed': 'Edge function publicada',
  'snapshot.collected': 'Snapshot coletado',
  'cron.installed': 'Extensão pg_cron instalada',
  'cron.created': 'Agendamento criado',
  'cron.toggled': 'Agendamento ativado/pausado',
  'cron.deleted': 'Agendamento excluído',
  'cron.ran_now': 'Agendamento executado manualmente',
  'cron.no_sleep_installed': 'No Sleep instalado',
  'cron.no_sleep_removed': 'No Sleep removido',
  'backup.created': 'Backup gerado',
  'backup.failed': 'Backup falhou',
  'backup.downloaded': 'Backup baixado',
  'backup.deleted': 'Backup excluído',
  'backup.rows_restored': 'Linhas restauradas de backup',
  'agent.token_created': 'Token de agente criado',
  'agent.token_revoked': 'Token de agente revogado',
  'agent.token_updated': 'Token de agente alterado',
}

/** Ações destrutivas ganham destaque visual na tela de auditoria. */
export const DESTRUCTIVE_ACTIONS = new Set([
  'data.row_deleted',
  'project.paused',
  'sql.migration_applied',
  'function.deployed',
  'auth.user_deleted',
  'project.archived',
  'account.deleted',
  'client.deleted',
  'storage.file_deleted',
  'sql.executed',
  'project.keys_revealed',
  'cron.created',
  'cron.deleted',
  'cron.ran_now',
  'cron.installed',
  'cron.no_sleep_installed',
  'cron.no_sleep_removed',
  'backup.downloaded',
  'backup.deleted',
  'backup.rows_restored',
  'agent.token_created',
  'agent.token_revoked',
])
